name: 'KeepActionAlive'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # æ¯å‘¨æ—¥è§¦å‘

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Empty Commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit --allow-empty -m "ğŸ¤– Automated weekly activity ping"

      - name: Push Changes
        run: git push origin HEAD
